# encoding: utf-8
# module pandas._libs.tslibs.np_datetime
# from C:\Users\siddh\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\_libs\tslibs\np_datetime.cp37-win_amd64.pyd
# by generator 1.146
# no doc

# imports
import builtins as __builtins__ # <module 'builtins' (built-in)>

# no functions
# classes

class OutOfBoundsDatetime(ValueError):
    # no doc
    def __init__(self, *args, **kwargs): # real signature unknown
        pass

    __weakref__ = property(lambda self: object(), lambda self, v: None, lambda self: None)  # default
    """list of weak references to the object (if defined)"""



# variables with complex values

__loader__ = None # (!) real value is ''

__pyx_capi__ = {
    '_string_to_dts': None, # (!) real value is ''
    'check_dts_bounds': None, # (!) real value is ''
    'cmp_scalar': None, # (!) real value is ''
    'dt64_to_dtstruct': None, # (!) real value is ''
    'dtstruct_to_dt64': None, # (!) real value is ''
    'get_datetime64_unit': None, # (!) real value is ''
    'get_datetime64_value': None, # (!) real value is ''
    'get_timedelta64_value': None, # (!) real value is ''
    'pydate_to_dt64': None, # (!) real value is ''
    'pydatetime_to_dt64': None, # (!) real value is ''
    'reverse_ops': None, # (!) real value is ''
    'td64_to_tdstruct': None, # (!) real value is ''
}

__spec__ = None # (!) real value is ''

__test__ = {}

